// <auto-generated />
using System;
using AirportAPI.Areas.Identity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirportAPI.Migrations
{
    [DbContext(typeof(Wx1Context))]
    [Migration("20230627003730_addformsandidentity")]
    partial class addformsandidentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AirportAPI.Entities.Formdatum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Airport")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("airport");

                    b.Property<string>("Comments")
                        .HasMaxLength(10000)
                        .HasColumnType("varchar(10000)")
                        .HasColumnName("comments");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("lastName");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("formdata", (string)null);
                });

            modelBuilder.Entity("AirportAPI.Entities.Wxdatum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<float?>("Humidity")
                        .HasColumnType("float")
                        .HasColumnName("humidity");

                    b.Property<string>("Identifier")
                        .HasColumnType("text")
                        .HasColumnName("identifier");

                    b.Property<float?>("Temperature")
                        .HasColumnType("float")
                        .HasColumnName("temperature");

                    b.Property<float?>("Winddirection")
                        .HasColumnType("float")
                        .HasColumnName("winddirection");

                    b.Property<float?>("Windspeed")
                        .HasColumnType("float")
                        .HasColumnName("windspeed");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("wxdata", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
